### ISSUE TITLE
Hearth button shows non-favorite hearth toy when "only show favorite hearth toys" option checked.

### ISSUE THREAD

**Issue by XtroTheArctic** [MuffinManKen/AutoBar#18]
![image](https://user-images.githubusercontent.com/6631429/198853148-56ff6d31-bf95-4f17-84a2-bb998f595470.png)

**Comment by MuffinManKen** [comment]
Release 10.0.2.00 (just uploaded) should fix this.  Let me know.

**Comment by XtroTheArctic** [comment]
It works now. Thank you!
