### ISSUE TITLE
Settings not saved with 10.0.0.03

### ISSUE THREAD

**Issue by Auxiliotest** [MuffinManKen/AutoBar#20]
Since the update today, settings are not saved. Even just a reload resets every setting .

**Comment by MuffinManKen** [comment]
Is version 10.0.0.05 working for you?  If not, please attach your SaveVariables file so I can try to see what's going on.

**Comment by Auxiliotest** [comment]
Yes it is working fine thx :)

**Comment by Auxiliotest** [comment]
I had to delete the saved variables file to make it work though
