### ISSUE TITLE
Bad Argument on 1541

### ISSUE THREAD

**Issue by rmtaft** [MuffinManKen/AutoBar#21]
this pops up every time its loaded
no bars will display

`
3x Interface/AddOns/AutoBar/AutoBarOptions.lua:1541: bad argument #1 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Interface/AddOns/AutoBar/AutoBarOptions.lua"]:1541: in function `CreateBarOptions'
[string "@Interface/AddOns/AutoBar/AutoBarOptions.lua"]:1415: in function `CreateOptionsAce3'
[string "@Interface/AddOns/AutoBar/AutoBarOptions.lua"]:88: in function `InitializeOptions'
[string "@Interface/AddOns/AutoBar/Core.lua"]:241: in function `InitializeZero'
[string "@Interface/AddOns/AutoBar/Core.lua"]:407: in function `?'
[string "@Interface/AddOns/AutoBar/Core.lua"]:141: in function <Interface/AddOns/AutoBar/Core.lua:136>

Locals:
(*temporary) = "Configuration for %s"
(*temporary) = nil
(*temporary) = "string expected, got nil"

`

**Comment by MuffinManKen** [comment]
v10.0.2.01 should fix this

**Comment by MuffinManKen** [comment]
Are you still having this issue?

**Comment by MuffinManKen** [comment]
Closing due to lack of response.

**Comment by rmtaft** [comment]
Can I get you a month of wow so it's not so frustrating ?. 1 though 20 is
free also. Then again. You may just not want to put the needle back in the
arm hahahHa
