### ISSUE TITLE
Bug: Swapping specs causes repeating error until reloading

### ISSUE THREAD

**Issue by nancikennedy** [MuffinManKen/AutoBar#22]
I deliberately deleted both the current and the .bak file to start fresh when this popped up, just to make sure it wasn't some old setting I had. Anyway, when you switch talent specs this error pops up and just keeps popping up. The error count just keeps increasing like crazy, and I had to reload to fix it.

282x AutoBar/AutoBarSearch.lua:1086: attempt to call field 'delete_found_item' (a nil value)
[string "@AutoBar/AutoBarSearch.lua"]:1086: in function `ScanRegisteredSpells'
[string "@AutoBar/Core.lua"]:1159: in function `UpdateSpells'
[string "@AutoBar/Core.lua"]:1078: in function <AutoBar/Core.lua:1060>

Locals:
self = <table> {
 ScanRegisteredSpells = <function> defined @AutoBar/AutoBarSearch.lua:1079
 current = <table> {
 }
 ScanBag = <function> defined @AutoBar/AutoBarSearch.lua:1189
 UpdateScan = <function> defined @AutoBar/AutoBarSearch.lua:1015
 sorted = <table> {
 }
 MarkBagDirty = <function> defined @AutoBar/AutoBarSearch.lua:1034
 registered_spells = <table> {
 }
 RegisterToy = <function> defined @AutoBar/AutoBarSearch.lua:909
 MarkInventoryDirty = <function> defined @AutoBar/AutoBarSearch.lua:1039
 Initialize = <function> defined @AutoBar/AutoBarSearch.lua:969
 ScanRegisteredMacroText = <function> defined @AutoBar/AutoBarSearch.lua:1115
 GetRegisteredSpellInfo = <function> defined @AutoBar/AutoBarSearch.lua:59
 space = <table> {
 }
 Empty = <function> defined @AutoBar/AutoBarSearch.lua:985
 ScanRegisteredMacros = <function> defined @AutoBar/AutoBarSearch.lua:1094
 ScanRegisteredToys = <function> defined @AutoBar/AutoBarSearch.lua:1066
 RegisterMacroText = <function> defined @AutoBar/AutoBarSearch.lua:869
 registered_toys = <table> {
 }
 RegisterSpell = <function> defined @AutoBar/AutoBarSearch.lua:835
 RegisterMacro = <function> defined @AutoBar/AutoBarSearch.lua:939
 ScanDirtyBags = <function> defined @AutoBar/AutoBarSearch.lua:1045
 ScanInventory = <function> defined @AutoBar/AutoBarSearch.lua:1166
 found = <table> {
 }
 dirty = <table> {
 }
 items = <table> {
 }
 inventory_cache = <table> {
 }
 registered_macros = <table> {
 }
 registered_macro_text = <table> {
 }
 ScanAll = <function> defined @AutoBar/AutoBarSearch.lua:1215
 bag_cache = <table> {
 }
 ScanBagsInCombat = <function> defined @AutoBar/AutoBarSearch.lua:1056
 Reset = <function> defined @AutoBar/AutoBarSearch.lua:1001
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Portal: Dalaran - Northrend = <table> {
 }
 Teleport: Dalaran - Northrend = <table> {
 }
 Teleport: Undercity = <table> {
 }
 Teleport: Stonard = <table> {
 }
 Teleport: Oribos = <table> {
 }
 Portal: Tol Barad = <table> {
 }
 Teleport: Dalaran - Broken Isles = <table> {
 }
 Teleport: Tol Barad = <table> {
 }
 Teleport: Orgrimmar = <table> {
 }
 Fishing = <table> {
 }
 Portal: Dazar'alor = <table> {
 }
 Archaeology = <table> {
 }
 Teleport: Silvermoon = <table> {
 }
 Mobile Banking = <table> {
 }
 Teleport: Thunder Bluff = <table> {
 }
 Portal: Orgrimmar = <table> {
 }
 Portal: Stonard = <table> {
 }
 Arcane Intellect = <table> {
 }
 Counterspell = <table> {
 }
 Teleport: Shattrath = <table> {
 }
 Ice Block = <table> {
 }
 Tailoring = <table> {
 }
 Prismatic Barrier = <table> {
 }
 Cooking = <table> {
 }
 Survey = <table> {
 }
 Portal: Warspear = <table> {
 }
 Enchanting = <table> {
 }
 Disenchant = <table> {
 }
 Teleport: Hall of the Guardian = <table> {
 }
 Portal: Silvermoon = <table> {
 }
 Ancient Portal: Dalaran = <table> {
 }
 Conjure Refreshment = <table> {
 }
 Portal: Dalaran - Broken Isles = <table> {
 }
 Portal: Oribos = <table> {
 }
 Portal: Undercity = <table> {
 }
 Portal: Shattrath = <table> {
 }
 Teleport: Dazar'alor = <table> {
 }
 Revive Battle Pets = <table> {
 }
 Portal: Vale of Eternal Blossoms = <table> {
 }
 Portal: Thunder Bluff = <table> {
 }
 Teleport: Warspear = <table> {
 }
 Slow Fall = <table> {
 }
 Teleport: Vale of Eternal Blossoms = <table> {
 }
 Conjure Mana Gem = <table> {
 }
 Ancient Teleport: Dalaran = <table> {
 }
 Cooking Fire = <table> {
 }
 Invisibility = <table> {
 }
}
(for control) = "Prismatic Barrier"
name = "Prismatic Barrier"
info = <table> {
 spell_id = 235450
 can_cast = false
 no_spell_check = false
}
can_cast = false
(*temporary) = nil
(*temporary) = "Prismatic Barrier"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Prismatic Barrier"
(*temporary) = "attempt to call field 'delete_f

**Comment by MuffinManKen** [comment]
Version 10.0.2.02 should fix this.  Please let me know either way.

**Comment by nancikennedy** [comment]
I've swapped specs a bunch of times tonight, in configuration with a bunch of different addons...and it has not cropped up!
