### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by OttoDeFe** [MuffinManKen/AutoBar#23]
I was one of the people who had the microstutters on the live client. I found that AutoBar was doing some heavy memory growth since prepatch phase 2 on my system. It seems like there's a small memory leak somewhere that was affecting my client. I wish I had better info.  Love the AddOn and am aware it could just be me.

**Comment by MuffinManKen** [comment]
How much memory are we talking about here?  After you've been in the world for a minute or 2, it shouldn't be growing.

**Comment by teddyzipper** [comment]
I also get micro stutters the memory doesn't seem to increase past loading but when i use the add on "addon usage" which lets me see [CPU usage](https://imgur.com/a/nHaDqw4) and autobar shows as using alot more than anything else, could this be connected?

**Comment by teddyzipper** [comment]
ok, when i enable "log performance" no events show up([aside from what pops on load](https://imgur.com/a/rjoYYBf)). if i enable "[log events](https://imgur.com/a/aTCLHfP)" it spits out this, i get stutters roughly as it "shows new events" if i throttle events the stutter is just in time with that.
might be worth mentioning i'm running the game/addon off a mechanical hard-drive, could this be causing this issue?

**Comment by MuffinManKen** [comment]
Is this still an issue?  I removed some unnecessary logging, which should have helped at least a bit.

**Comment by MuffinManKen** [comment]
Closing due to lack of response.
