### ISSUE TITLE
 attempt to index field 'account' - autobar does not load

### ISSUE THREAD

**Issue by thecneu** [MuffinManKen/AutoBar#24]
Interface/AddOns/AutoBar/AutoBarDB.lua:355: attempt to index field 'account' (a nil value)

This error doesn't allow autobar to load at all. No options or anything. I had no addons running at the time. If I deleted the SavedVariables and start over it works. However I have around 10 years of custom changes. So I'd love to stay within my old save file. I have attached my saved file. Worse case I start over but if you wanna take a look will be great.

Thanks
[AutoBar.zip](https://github.com/MuffinManKen/AutoBar/files/10037034/AutoBar.zip)

**Comment by MuffinManKen** [comment]
This should be fixed in v10.0.2.03, please let me know.

**Comment by MuffinManKen** [comment]
Closing due to lack of response.
