### ISSUE TITLE
Autobars don't load - bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by txbacon** [MuffinManKen/AutoBar#25]
2x Interface/AddOns/AutoBar/AutoBarDB.lua:356: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/AutoBar/AutoBarDB.lua"]:356: in function <Interface/AddOns/AutoBar/AutoBarDB.lua:297>
[string "@Interface/AddOns/AutoBar/AutoBarDB.lua"]:407: in function `InitializeDB'
[string "@Interface/AddOns/AutoBar/Core.lua"]:240: in function `InitializeZero'
[string "@Interface/AddOns/AutoBar/Core.lua"]:407: in function `?'
[string "@Interface/AddOns/AutoBar/Core.lua"]:141: in function <Interface/AddOns/AutoBar/Core.lua:136>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by MuffinManKen** [comment]
This should be fixed in v10.0.2.04. Please let me know.

**Comment by txbacon** [comment]
Yep works now, thanks!
