### ISSUE TITLE
Bug: Mount Button Sort Option not working

### ISSUE THREAD

**Issue by nancikennedy** [MuffinManKen/AutoBar#29]
On Retail, with v10.0.2.04 installed, checking the "Reverse Sort Order" option for the Mount Button doesn't change the sort order.

**Comment by MuffinManKen** [comment]
You may need to do a /reloadui after changing the setting.

**Comment by MuffinManKen** [comment]
Does it work after a reload?

**Comment by MuffinManKen** [comment]
The latest release may have fixed this, please let me know.
