### ISSUE TITLE
Trinket Options Missing or not updating

### ISSUE THREAD

**Issue by ColdThief** [MuffinManKen/AutoBar#32]
The trinket section on the basic bar is not updating correctly with new trinkets and just shows the slash command for it. It is also only showing one of the buttons but is currently just flickering.

A reload of the UI made both trinket buttons disappear completely.

**Comment by MuffinManKen** [comment]
This should be fixed in v10.0.2.05

**Comment by ColdThief** [comment]
Looks good, thanks! Thanks for keeping it up to date, I know it could be hard without playing.
