### ISSUE TITLE
Bug? Some buttons not filtering properly

### ISSUE THREAD

**Issue by nancikennedy** [MuffinManKen/AutoBar#34]
1) "Mana / Rage / Energy" button is also showing Healing Potions
2) "Heal" button is showing Healing and Mana Potions
3) "Buff" button is showing Mana and Healing Potions

**Comment by MuffinManKen** [comment]
That definitely seems wrong.  Can you give me some specific examples of each problem?

**Comment by nancikennedy** [comment]
Okay, here goes....first image, with "Show Empty Buttons" checked
Btn 1: Custom Racial button, ignore this
Btn 2: Custom Combat Potion button
Btn 3: Potion Cooldown: Combat (Built-In) This should contain things like what I put in button 2, but it is empty and it shouldn't be??
Btn 4&5: Ignore these, they are working as intended. (Battle Standards and Drums)
Btn 6: Heal (Built-In) This should contain only Healing Potions. I rounded up as many healing and mana pots as I could find, just to illustrate that it's not filtering properly.
Btn 7:  Bandages (Built-In). This is working with previous bandages. DF's Wildercloth Bandages are itemids 194048, 194049 & 194050. Including this as an FYI.
Btn 8: Mana / Rage / Energy (Built-In) This should contain only resource potions, but it is also showing healing potions.

Bar:
![basic bar](https://user-images.githubusercontent.com/8207666/207958761-943edf27-748e-405d-93d2-233da4b5bd28.JPG)

Btn 2:

![my combat potion](https://user-images.githubusercontent.com/8207666/207959541-8739fe1f-c16a-4eec-bbef-552840db23e1.JPG)

Btn 3:
![image](https://user-images.githubusercontent.com/8207666/207959872-f965664d-a1e2-4d51-98d3-f50c35261a95.png)

Btn 6:
![image](https://user-images.githubusercontent.com/8207666/207960856-b5c49f80-9bad-479a-86ea-c5d786222cf6.png)

Btn 8:
![image](https://user-images.githubusercontent.com/8207666/207962383-ef065f0b-9d01-464e-844a-35244c89c829.png)

**Comment by nancikennedy** [comment]
As for the Built-In Buffs button, I can't find my original screencap I took and it's not currently showing anything improper. I either hallucinated it, or you fixed it. :)

**Comment by nancikennedy** [comment]
I've come across a few more inconsistencies in what is showing or not, in other categories (e.g. some shaman totems are missing from my AB for my shaman). Do you want me to make separate tickets on them?

**Comment by MuffinManKen** [comment]
If there are still missing items/spells, please open a new ticket for it.
