### ISSUE TITLE
Food Buff / Weapon buff buttons not showing up

### ISSUE THREAD

**Issue by thecneu** [MuffinManKen/AutoBar#35]
Some food buffs and weapon buffs are not showing up. I am not able to get Hopefully Healthy (df), Thrice Spiced Mammoth Kabob(df), Grimestone Stew (bfa), Kul Tiramisu(bfa). Also Shadowcore Oil from shadowlands doesn't show up. I deleted my saved variables to start from scratch still same issue. Basic dragonflight foods show up tho. 

Thanks!!

On newest version 10.0.2.06

**Comment by ehrw** [comment]
Same. This expansion has a lot of these things at different levels that autobar would be awesome for. Tbh the biggest reason I'm still using autobar after all these years. Would love if it was fixed <3

**Comment by crzykidd** [comment]
@MuffinManKen I added some food, fishing etc.. to #42.  However I am not sure where to add the new Runes likes
https://www.wowhead.com/item=194820/howling-rune
If you could tell me where these would be located I can add them to the files.

**Comment by crzykidd** [comment]
This should be fixed now, if there is a food that is missing open a new issue.

**Comment by MuffinManKen** [comment]
Assuming fixed.
