### ISSUE TITLE
Error when doing anything with Buttons.

### ISSUE THREAD

**Issue by Nevyr28** [MuffinManKen/AutoBar#37]
Getting the following error when trying to do anything with the buttons; move, edit, or create new ones with custom categories.

 

409x Interface\AddOns\AutoBarWrath\AutoBarClassBar.lua:722: attempt to perform arithmetic on field 'default_button_h' (a nil value)
[string "@Interface\AddOns\AutoBarWrath\AutoBarClassBar.lua"]:722: in function `RefreshButtonLayout'
[string "@Interface\AddOns\AutoBarWrath\AutoBarClassBar.lua"]:545: in function `RefreshLayout'
[string "@Interface\AddOns\AutoBarWrath\Core.lua"]:1232: in function `UpdateActive'
[string "@Interface\AddOns\AutoBarWrath\Core.lua"]:868: in function `MoveButtonsModeOn'
[string "@Interface\AddOns\AutoBarWrath\Core.lua"]:855: in function <Interface\AddOns\AutoBarWrath\Core.lua:851>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-85.lua"]:45: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:43>
[string "@Interface\AddOns\Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-85.lua"]:827: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:649>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:66: in function <Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:64>
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:300: in function `Fire'
[string "@Interface\AddOns\Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

**Comment by MuffinManKen** [comment]
Did the new Wrath release (v3.04.1.00) fix this?

**Comment by Nevyr28** [comment]
Yes all errors are gone with the new version. Thanks so much!
