### ISSUE TITLE
Food Buffs not showing up

### ISSUE THREAD

**Issue by crzykidd** [MuffinManKen/AutoBar#40]
Hopefully Healthy itemid 197777
Sizzling Seafood Medley itemid 197784
Fated Fortune Cookie  itemid 197792

**Comment by crzykidd** [comment]
Fixed in Pull request #41

**Comment by crzykidd** [comment]
Fixed in PR #42 also added Thousandbone Tongueslicer to the list.

**Comment by MuffinManKen** [comment]
Are they all there now?

**Comment by crzykidd** [comment]
Ya I think so. at least the foods I use :)   If I find more I will do a PR.   Thanks for updating and rolling it out.
