### ISSUE TITLE
Buttons not responding when cVar ActionButtonUseKeyDown is set to 1 [v10.0.2.08]

### ISSUE THREAD

**Issue by brykrys** [MuffinManKen/AutoBar#44]
I traced this to commit https://github.com/MuffinManKen/AutoBar/commit/f09245863631c22b813fd55e30f925f9cc7296f2 "Removed stupid hack required by Dragonflight which caused double-clicks in Wrath"

Confirmed the stupid hack **is** still required in Dragonflight...

Confirmed that by changing cVar ActionButtonUseKeyDown to 0 the Autobar buttons will work (but this causes at least one of my other AddOns to stop working).

By manually undoing the changes in the above commit, confirmed that Autobar then works with cVar ActionButtonUseKeyDown set to 1

Note that the default value for cVar ActionButtonUseKeyDown is 1.

**Comment by MuffinManKen** [comment]
Thanks for digging into it.  It should be fixed now.
