### ISSUE TITLE
Permanent Item enchantments are missing

### ISSUE THREAD

**Issue by crzykidd** [MuffinManKen/AutoBar#45]
@MuffinManKen after that last pull it seems like all of these items didn't make it into the datastore.  These are DF armor/ring enchantments and should go under ["Muffin.ItemEnchant.Permanent"]    I added them back to my copy and things show up again.    

Thanks,

199938, 199939, 199940, 199941, 199942, 199943, 199944, 199945, 199946, 199947, 199948, 199949, 199950, 199951, 199952, 199953, 199954, 199955, 199956, 199957, 199958, 199959, 199960, 199961, 199962, 199963, 199964, 199965, 199966, 199967, 199968, 199969, 199970, 199971, 199972, 199973, 199974, 199975, 199976, 199977, 199978, 199979, 199980, 199981, 199982, 199983, 199984, 199985, 199986, 199987, 199988, 199989, 199990, 199991, 199992, 199993, 199994, 199995, 199996, 199997, 199998, 199999, 200000, 200001, 200002, 200003, 200004, 200005, 200006, 200007, 200008, 200009, 200010, 200011, 200012, 200013, 200014, 200015, 200016, 200017, 200018, 200019, 200020, 200021, 200022, 200023, 200024, 200025, 200026, 200027, 200028, 200029, 200030, 200031, 200032, 200033, 200034, 200035, 200036, 200037, 200038, 200039, 200040, 200041, 200042, 200043, 200044, 200045, 200046, 200047, 200048, 200049, 200050, 200051, 200052, 200053, 200054, 200055, 200056, 200057, 200058, 200059

**Comment by MuffinManKen** [comment]
I'll try to make some time to look at why the dataminer missed them.  Thanks for the info!

**Comment by MuffinManKen** [comment]
I just uploaded a version with more datamining based on the info you gave.  Please let me know if more stuff was missed.

**Comment by crzykidd** [comment]
@MuffinManKen still missing big chunks.   
199943-199952
199966-199978
199985-199994
200008-200020
200027-200036
200050-200059

**Comment by MuffinManKen** [comment]
Any better now?

**Comment by MuffinManKen** [comment]
Closing due to lack of response; assuming fixed.
