### ISSUE TITLE
Wildercloth Bandages are Missing from the Bandage Button

### ISSUE THREAD

**Issue by b-morgan** [MuffinManKen/AutoBar#46]
See [https://www.curseforge.com/wow/addons/auto-bar/issues/24](https://www.curseforge.com/wow/addons/auto-bar/issues/24).

**Comment by MuffinManKen** [comment]
How about now?

**Comment by b-morgan** [comment]
Nope. There are three qualities of Wildercloth Bandage, 
[https://www.wowhead.com/item=194048/wildercloth-bandage](https://legacy.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.wowhead.com%252fitem%253d194048%252fwildercloth-bandage)
[https://www.wowhead.com/item=194049/wildercloth-bandage](https://legacy.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.wowhead.com%252fitem%253d194049%252fwildercloth-bandage)

[https://www.wowhead.com/item=194050/wildercloth-bandage](https://legacy.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.wowhead.com%252fitem%253d194050%252fwildercloth-bandage)

10.0.7.01 only added one, 194048:33977. The other two are 194049:39603 and 194050:46152.
