### ISSUE TITLE
[Classic ERA] AutoBar:RegisterDB("AutoBarDB", nil, "class") causing lua error on 1.14.4

### ISSUE THREAD

**Issue by Lefaux** [MuffinManKen/AutoBar#50]
With the last update from 23.08.2023 it seems a pretty big API change has been introduced.
AutoBar fails with 
`AutoBarClassic/AutoBarDB.lua:128: attempt to index field 'account' (a nil value)
[string "@AutoBarClassic/AutoBarDB.lua"]:128: in function `InitializeDB'
[string "@AutoBarClassic/Core.lua"]:241: in function `InitializeZero'
[string "@AutoBarClassic/Core.lua"]:418: in function `?'
[string "@AutoBarClassic/Core.lua"]:141: in function <AutoBarClassic/Core.lua:136>`

My knowledge of lua is not big enough to trace it down into the details of WoW but it feels like something that was public before no longer is public.

If you find the time to look into this I'd really appreciate it, since AutoBar has been a trusty companion of mine for a LONG time :)

**Comment by Lefaux** [comment]
@MuffinManKen Is there a way to hire you in some fashion?
I understand you no longer play the game, but I could provide you with everything you'd need.

Hit me up if you're interested :)

**Comment by Lefaux** [comment]
Interesting fact:
I cloned this repo and manually put together the release for Classic ERA here https://github.com/Lefaux/AutoBarClassic
From what I see so far, it seems to work.

Maybe it just takes a release?

**Comment by jasskin** [comment]
I am not seeing a published release on your Fork I downloaded the zip from the code page but still not working for me. Neither your fork or Muffins are showing up on PTR even under the addon list but it does load and through errors in game. I also don't see that the curseforge updater is picking up that I have it installed on the PTR.

**Comment by jasskin** [comment]
Re-installed the Addon from Curse it now at least is showing up.

**Comment by Lefaux** [comment]
I didn't test PTR to be honest.
On classic ERA EU it works for me - maybe the version in the TOC is wrong for the PTR?

**Comment by MuffinManKen** [comment]
So was the issue basically that the Classic API caught up with the Retail API?

**Comment by Lefaux** [comment]
@MuffinManKen It seems that blizzard has unified the clients and parts of the API (which makes a lot of sense if you ask me)
I'm not too deep into WoWs API, but what I saw isa that GetBagName() is no longer globally available but needs to be called via `C_Container.GetBagName()`

**Comment by MuffinManKen** [comment]
I'll get out a fix for this soon.  I've also launched a Kickstarter to do further development:
[](https://www.kickstarter.com/projects/2075655491/autobar-2023)
