### ISSUE TITLE
class action bars

### ISSUE THREAD

**Issue by KopyKat82** [MuffinManKen/AutoBar#53]
in wotlk classic   the dragonhawk aspect is missing

**Comment by jasskin** [comment]
Added Dragonhawk aspect. I have also updated mine to include some Priest and Mage updates.
[CachedSpells&ABCategoryData.zip](https://github.com/MuffinManKen/AutoBar/files/13037779/CachedSpells.ABCategoryData.zip)

**Comment by MuffinManKen** [comment]
> Added Dragonhawk aspect. I have also updated mine to include some Priest and Mage updates. [CachedSpells&ABCategoryData.zip](https://github.com/MuffinManKen/AutoBar/files/13037779/CachedSpells.ABCategoryData.zip)
> 
> extract to World of Warcart/_classic_/interface/Addons/AutoBarWrath/wrath

A PR, or at least a detailed list of changes, would be appreciated.

**Comment by MuffinManKen** [comment]
@jasskin Other than Dragonhawk, what other changes had you made?
