### ISSUE TITLE
error after 10.2.6

### ISSUE THREAD

**Issue by MrMime71** [MuffinManKen/AutoBar#54]
162757x Usage: local count = C_Item.GetItemCount(itemInfo [, includeBank, includeUses, includeReagentBank])
[string "=[C]"]: in function `GetItemCount'
[string "@AutoBar/AutoBarClassButton.lua"]:641: in function `IsActive'
[string "@AutoBar/AutoBarClassBar.lua"]:313: in function `UpdateActive'
[string "@AutoBar/Core.lua"]:1253: in function `UpdateActive'
[string "@AutoBar/Core.lua"]:1241: in function `UpdateAttributes'
[string "@AutoBar/Core.lua"]:1078: in function <AutoBar/Core.lua:1052>

Locals:
(*temporary) = "Usage: local count = C_Item.GetItemCount(itemInfo [, includeBank, includeUses, includeReagentBank])"

**Comment by MuffinManKen** [comment]
New release should take care of this.

**Comment by Alessandro-Barbieri** [comment]
I'm hitting this today on classic (SoD) version 1.15.0.00
