### ISSUE TITLE
WoW Classic, ATB throws error with quest items

### ISSUE THREAD

**Issue by Teax20** [MuffinManKen/AutoBar#57]
Greetings, after accepting a quest with a received quest item, ATB throws following error. The bar itself still functions.
Error comes with every quest i accepted so far where i get a quest item.

`Date: 2024-06-23 12:48:05
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/AutoBarClassic/Core.lua line 303:
   attempt to index local 'category' (a nil value)
Debug:
   [string "@Interface/AddOns/AutoBarClassic/Core.lua"]:303:
      Interface/AddOns/AutoBarClassic/Core.lua:296
   [string "@Interface/AddOns/AutoBarClassic/Core.lua"]:327: ?()
   [string "@Interface/AddOns/AutoBarClassic/Core.lua"]:137:
      Interface/AddOns/AutoBarClassic/Core.lua:111
Locals:
p_item_link = "|cffffffff|Hitem:17117::::::::18:::::::::|h[Rat Catcher's Flute]|h|r"
p_category_name = "Dynamic.Quest"
debug_me = false
category = nil
item_name = "Rat Catcher's Flute"
item_id = 17117
(*temporary) = "17117"
(*temporary) = "Rat Catcher's Flute"
(*temporary) = "Rat Catcher's Flute"
(*temporary) = 17117
(*temporary) = "17117"
(*temporary) = 17117
(*temporary) = "attempt to index local 'category' (a nil value)"
code = <table> {
 get_spell_name_by_name = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:355
 get_spell_icon_by_name = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:366
 GetIconForToyID = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:249
 IsUsableItem = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:297
 ToyGUID = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:222
 add_profile_data = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:383
 get_warning_log_string = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:213
 NVL = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:190
 log_warning = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:202
 make_set = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:68
 MacroTextGUID = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:238
 GetItemCount = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:407
 GetLogIndexForQuestID = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:422
 cache_spell_data = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:337
 Dump = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:169
 ClearNormalTexture = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:312
 get_spell_icon_by_name_fast = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:377
 GetIconForItemID = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:266
 class_uses_mana = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:77
 GetValidatedName = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:275
 is_table_empty = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarGlobals.lua:62
}
AutoBar = <table> {
 barList = <table> {
 }
 SetDifference = <function> defined @Interface/AddOns/AutoBarClassic/Core.lua:1004
 UpgradeBar = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarDB.lua:1274
 class = <table> {
 }
 UpgradeButton = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarDB.lua:1284
 OnProfileDisable = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarOptions.lua:534
 GetDraggingIndex = <function> defined @Interface/AddOns/AutoBarClassic/Core.lua:659
 MoveBarModeOn = <function> defined @Interface/AddOns/AutoBarClassic/Core.lua:785
 GetCategoriesItemDB = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarOptions.lua:475
 ButtonExists = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarDB.lua:1045
 char = <table> {
 }
 dockingFrames = <table> {
 }
 CreateBarOptions = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarOptions.lua:1534
 warning_log = <table> {
 }
 categoryValidateList = <table> {
 }
 barPositionDBList = <table> {
 }
 LIBKEYBOUND_ENABLED = <function> defined @Interface/AddOns/AutoBarClassic/Core.lua:755
 MoveButtonsModeOn = <function> defined @Interface/AddOns/AutoBarClassic/Core.lua:856
 Class = <table> {
 }
 inBG = false
 buttonDBList = <table> {
 }
 CLASS = "HUNTER"
 tcount = <function> defined @Interface/AddOns/AutoBarClassic/Core.lua:991
 MoveButtonsModeOff = <function> defined @Interface/AddOns/AutoBarClassic/Core.lua:868
 barButtonsDBList = <table> {
 }
 barValidateList = <table> {
 }
 RefreshButtonDBList = <function> defined @Interface/AddOns/AutoBarClassic/AutoBarDB.lua:966
 StupidLogEnable = <function> defined @Interface/AddOns/AutoBarClassic/Core.lua:925
 Debug
AddOns:
  Swatter, v3.4.6977 (SwimmingSeadragon)
  AutoBarClassic, v1.15.2.00
  BlizRuntimeLib v1.15.2.55140(EU) <enUS>
  (ck=8b`

**Comment by MuffinManKen** [comment]
Is this still occuring?

**Comment by MuffinManKen** [comment]
Closing due to lack of response.

**Comment by Alessandro-Barbieri** [comment]
This is still up
```
2x AutoBarClassic/Core.lua:303: attempt to index local 'category' (a nil value)
[string "@AutoBarClassic/Core.lua"]:303: in function <AutoBarClassic/Core.lua:296>
[string "@AutoBarClassic/Core.lua"]:327: in function `?'
[string "@AutoBarClassic/Core.lua"]:137: in function <AutoBarClassic/Core.lua:111>

Locals:
p_item_link = "|cffffffff|Hitem:15042::::::::60:::::::::|h[Pot de Termites vide]|h|r"
p_category_name = "Dynamic.Quest"
debug_me = false
category = nil
item_name = "Pot de Termites vide"
item_id = 15042
(*temporary) = "15042"
(*temporary) = "Pot de Termites vide"
(*temporary) = "Pot de Termites vide"
(*temporary) = 15042
(*temporary) = "15042"
(*temporary) = 15042
(*temporary) = "attempt to index local 'category' (a nil value)"
code = <table> {
 get_spell_name_by_name = <function> defined @AutoBarClassic/AutoBarGlobals.lua:355
 get_spell_icon_by_name = <function> defined @AutoBarClassic/AutoBarGlobals.lua:366
 GetIconForToyID = <function> defined @AutoBarClassic/AutoBarGlobals.lua:249
 IsUsableItem = <function> defined @AutoBarClassic/AutoBarGlobals.lua:297
 ToyGUID = <function> defined @AutoBarClassic/AutoBarGlobals.lua:222
 add_profile_data = <function> defined @AutoBarClassic/AutoBarGlobals.lua:383
 get_warning_log_string = <function> defined @AutoBarClassic/AutoBarGlobals.lua:213
 NVL = <function> defined @AutoBarClassic/AutoBarGlobals.lua:190
 log_warning = <function> defined @AutoBarClassic/AutoBarGlobals.lua:202
 make_set = <function> defined @AutoBarClassic/AutoBarGlobals.lua:68
 MacroTextGUID = <function> defined @AutoBarClassic/AutoBarGlobals.lua:238
 GetItemCount = <function> defined @AutoBarClassic/AutoBarGlobals.lua:407
 GetLogIndexForQuestID = <function> defined @AutoBarClassic/AutoBarGlobals.lua:422
 cache_spell_data = <function> defined @AutoBarClassic/AutoBarGlobals.lua:337
 Dump = <function> defined @AutoBarClassic/AutoBarGlobals.lua:169
 ClearNormalTexture = <function> defined @AutoBarClassic/AutoBarGlobals.lua:312
 get_spell_icon_by_name_fast = <function> defined @AutoBarClassic/AutoBarGlobals.lua:377
 GetIconForItemID = <function> defined @AutoBarClassic/AutoBarGlobals.lua:266
 class_uses_mana = <function> defined @AutoBarClassic/AutoBarGlobals.lua:77
 GetValidatedName = <function> defined @AutoBarClassic/AutoBarGlobals.lua:275
 is_table_empty = <function> defined @AutoBarClassic/AutoBarGlobals.lua:62
}
AutoBar = <table> {
 barList = <table> {
 }
 SetDifference = <function> defined @AutoBarClassic/Core.lua:1004
 UpgradeBar = <function> defined @AutoBarClassic/AutoBarDB.lua:1274
 class = <table> {
 }
 UpgradeButton = <function> defined @AutoBarClassic/AutoBarDB.lua:1284
 OnProfileDisable = <function> defined @AutoBarClassic/AutoBarOptions.lua:534
 GetDraggingIndex = <function> defined @AutoBarClassic/Core.lua:659
 MoveBarModeOn = <function> defined @AutoBarClassic/Core.lua:785
 GetCategoriesItemDB = <function> defined @AutoBarClassic/AutoBarOptions.lua:475
 ButtonExists = <function> defined @AutoBarClassic/AutoBarDB.lua:1045
 char = <table> {
 }
 dockingFrames = <table> {
 }
 CreateBarOptions = <function> defined @AutoBarClassic/AutoBarOptions.lua:1534
 warning_log = <table> {
 }
 categoryValidateList = <table> {
 }
 barPositionDBList = <table> {
 }
 LIBKEYBOUND_ENABLED = <function> defined @AutoBarClassic/Core.lua:755
 MoveButtonsModeOn = <function> defined @AutoBarClassic/Core.lua:856
 Class = <table> {
 }
 inBG = false
 buttonDBList = <table> {
 }
 CLASS = "MAGE"
 tcount = <function> defined @AutoBarClassic/Core.lua:991
 MoveButtonsModeOff = <function> defined @AutoBarClassic/Core.lua:868
 barButtonsDBList = <table> {
 }
 barValidateList = <table> {
 }
 RefreshButtonDBList = <function> defined @AutoBarClassic/AutoBarDB.lua:966
 StupidLogEnable = <function> defined @AutoBarClassic/Core.lua:925
 Deb'
```
