### ISSUE TITLE
new spell missing from autobar

### ISSUE THREAD

**Issue by Hermorah1981** [MuffinManKen/AutoBar#58]
hi,
with the start of phase 4 in season of discovery blizzard added a new spell called Fel Armor (SpellID 403619 apparently) to the warlocks. 
this spell should go in the shields categoy as it is consistent with spells like demon skin and demon armor.
I would deeply appreciate adding the spell to the category.

also 'summon incubus' (SpellID 713 I believe) should be in the class pet category. this category already has the succubus in it so adding the succubus wouldn't be of great importance as those 2 spells are just gender variations of the same pet, so it's more a matter of demon gender equality :-P

**Comment by Alessandro-Barbieri** [comment]
> hi, with the start of phase 4 in season of discovery blizzard added a new spell called Fel Armor (SpellID 403619 apparently) to the warlocks. this spell should go in the shields categoy as it is consistent with spells like demon skin and demon armor. I would deeply appreciate adding the spell to the category.
> 

I'll add this in the next pull request

> also 'summon incubus' (SpellID 713 I believe) should be in the class pet category. this category already has the succubus in it so adding the succubus wouldn't be of great importance as those 2 spells are just gender variations of the same pet, so it's more a matter of demon gender equality :-P

Should be in the last update

**Comment by MuffinManKen** [comment]
Fel Armor is in v1.15.4.01
