### ISSUE TITLE
11.0

### ISSUE THREAD

**Issue by gruubar** [MuffinManKen/AutoBar#60]
Sorry that I'm not versed enough with Git to do a proper PR but I was able to get most Autobar functionality working in 11.02 by changing the 2 occurrences of GetSpellLink(p_spell_name) to C_Spell.GetSpellLink(p_spell_name) in AutoBarSearch.lua

and commenting out any InterfaceOptions_AddCategory calls in the Autobarconfig.lua
I think this broke the "integrated" addon config menu but /autobar config menus look normal to me.

I hope this helps other people using Autobar.
Thanks for all the years of upkeep on this, Ken!

**Comment by professionaltart** [comment]
Not sure what/if anyone else needs updating, @MuffinManKen , but I've submitted a PR for some of the changes mentioned by @gruubar and some mentioned over on the Curseforge page

**Comment by MuffinManKen** [comment]
I've uploaded a new version that should integrate all those fixes.
