### ISSUE TITLE
Change in macros and keybindings?

### ISSUE THREAD

**Issue by Fathersin** [MuffinManKen/AutoBar#62]
I'm not sure what was changed. Since I was on hiatus for a few seasons and there were other addons to fill in what I would normally do myself, I've been lazy and not looked anything up. I do know one of the addons I use I bound a macro at WW release on 23rd/24th but it doesn't let you have it on a bar?  Then for the mop remix is has been impossible to bind a key to some of the new buttons for the event buttons you get. /shrug

With that said, I'm not sure if that is related or operator error (Me). 

```
1x ...Ons/AutoBar/libs/LibKeyBound-1.0-100002/LibKeyBound-1.0.lua:106: CreateFrame(): Couldn't find inherited node "OptionsCheckButtonTemplate"
[string "=[C]"]: in function `CreateFrame'
[string "@AutoBar/libs/LibKeyBound-1.0-100002/LibKeyBound-1.0.lua"]:106: in function `Initialize'
[string "@AutoBar/libs/LibKeyBound-1.0-100002/LibKeyBound-1.0.lua"]:683: in function <...Ons/AutoBar/libs/LibKeyBound-1.0/LibKeyBound-1.0.lua:677>

Locals:
(*temporary) = "CheckButton"
(*temporary) = "KeyboundDialogCheck"
(*temporary) = KeyboundDialog {
 PixelSnapDisabled = true
 Center = Texture {
 }
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
}
(*temporary) = "OptionsCheckButtonTemplate"

```

**Comment by MuffinManKen** [comment]
Closing as fixed, if this isn't the case, please re-open with more info on what's broken.
