### ISSUE TITLE
Error when clicking "New" in Bars options tab

### ISSUE THREAD

**Issue by foopex** [MuffinManKen/AutoBar#63]
Error when clicking "New" in Bars options tab.  Also happens when this is the only mod enabled.  WOW version 11.0.2

```
11x AutoBar/AutoBarOptions.lua:746: attempt to index field 'Bar' (a nil value)
[string "@AutoBar/AutoBarOptions.lua"]:746: in function <AutoBar/AutoBarOptions.lua:745>
[string "=[C]"]: ?
[string "@AutoBar/libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@AutoBar/libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:839: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:661>
[string "=[C]"]: ?
[string "@AutoBar/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <AutoBar/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@AutoBar/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@AutoBar/libs/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...oBar/libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Bar' (a nil value)"
AB = <table> {
 UITK = <table> {
 }
 types = <table> {
 }
 AutoBarConfig = <table> {
 }
 MacroTextCategory = <table> {
 }
 LibKeyBound = <table> {
 }
 ToyCategory = <table> {
 }
 bar = <table> {
 }
 CategoryClass = <table> {
 }
 CustomCategory = <table> {
 }
 SpellsCategory = <table> {
 }
 ItemsCategory = <table> {
 }
 code = <table> {
 }
 LibStickyFrames = <table> {
 }
 WHATSNEW_TEXT = " - Fix not being able to drag bars
 - Fix not being able to keybind
 - I'm not playing WoW, so if things are missing or broken make sure you report them with as much detail as you can.
|n"
 events = <table> {
 }
}
L = <table> {
 Consumable.Buff.Resistance.Target = "Consumable.Buff.Resistance.Target"
 HearthIncludeAncientDalaran = "Include Ancient Dalaran"
 Consumable.Buff Group.Melee.Target = "Buff: Melee Target"
 Show Minimap Icon = "Show Minimap Icon"
 Key Bindings = "Key Bindings"
 Summon A Random Pet = "Summon Random Pet|n|cFFFFD100Summon a random pet from your pet journal|r"
 MountShowSummonRandom = "Summon a Random Favourite Mount"
 Raid 5 = "Raid Moon"
 AutoBarClassBarWarrior = "Warrior"
 Consumable.Buff Group.General.Target = "Buff: General Target"
 Shared = "Shared"
 AutoBarButtonBear = "Bear"
 AutoBarButtonWaterBuff = "Water Buff"
 LEFT = "Left"
 AutoBarButtonTravel = "Travel"
 Muffin.Covenant.Anima = "Muffin.Covenant.Anima"
 Consumable.Weapon Buff.Poison.Instant = "Instant Poison"
 AutoBarButtonBoomkinTree = "Tree of Life / Boomkin"
 Muffin.Covenant.Wildseed = "Muffin.Covenant.Wildseed"
 Muffin.Order Hall.Order Resources = "Muffin.Order Hall.Order Resources"
 Consumable.Food.Pet.Fungus = "Food: Pet Fungus"
 Snap Bars while moving = "Snap Bars while moving"
 Reset Bars = "Reset Bars"
 Consumable.Cooldown.Stone.Rejuvenation.Dreamless Sleep = "Dreamless Sleep"
 Consumable.Food.Edible.Combo.Conjured = "Food: combo health & mana gain, conjured"
 AutoBarButtonER = "ER"
 Consumable.Buff.Resistance.Self = "Consumable.Buff.Resistance.Self"
 AutoBarCooldownHeader = "Potion & Stone Cooldown"
 Non Combat Only = "Non Combat Only"
 Consumable.Buff Group.Caster.Target = "Buff: Caster Target"
 AutoBarButtonMiscFun = "Misc, Fun"
 Remove this Button from the Bar = "Remove this Button from the Bar"
 Misc.Spell.Mount.Flying.Fast = "Mounts: Fast Flying"
 Muffin.Skill.Archaeology.Lodestone = "Muffin.Skill.Archaeology.Lodestone"
 BOTTOMLEFT = "Bottom Left"
 Consumable.Buff.Armor = "Buff: Armor"
 AutoBarClassBarRogue = "Rogue"
 Ctrl-Shift-Click = "Ctrl-Shift-Click"
 Spell.Totem.Earth = "Earth Totem"
 Always keep Popups open for %s = "Always keep Popups open for %s"
 AutoBarButtonToyBox = "Toy Box"
 Spell.Class.Pets2 = "Pet Combat"
 SelfCast using Right click = "SelfCast using Right click"
 ToyBoxOnlyFavourites = "Only Show Favourites"
 BOTTOMRIGHT = "Bottom Right"
 Misc.Lockboxes = "Lockboxes"
 SLASHCMD_LONG = "autobar"
 Consumable.Buff.Health = "Buff: Health"
 MountShowNonFavourites = "Show Non-Favourites"
 Consumable.Buff Pet = "Buff: Pet"
 Spell.Track = "Spell.Track"
 AutoBarButtonSunsongRanch = "Sunsong Ranch"
 U = "U"
 Button Height = "Button Height"
 Spell.Sting = "Sting"
 AutoBarButtonRotationDrums = "Rotation: Drums"
 Tradeskill.Tool.Fishing.Tool = "Fishing Poles"
 Misc.Spell.Mount.Flying.Slow = "Mounts: Slow Flying"
 Skin the Buttons = "Skin the Buttons"
 Consumable.Bandage.Battleground.Warsong Gulch = "Warsong Bandages"
 Consumable.Buff.Dodge = "Buff: Dodge"
 Raid 2 = "Raid Circle"
 TOP = "Top"
 Consumable.Cooldown.Potion.Health.PvP = "Heal Potions: Battleground"
 Consumable.Buff.Intellect = "Buff: Intellect"
 Consumable.Weapon Buff.Poison.Crippling = "Crippling Poison"
 FadeOut takes this amount of time. = "FadeOut takes this amount of time"
 Hide %s = "Hide %s"
 Consumable.Buff Type.Guardian = "Buff: Guardian Elixir"
 Misc.Usable.Fun = "Fun Items"
 Muffin.Order Hall.Ancient Mana = "Muffin.Order Hall.Ancient Mana"
 Misc.Mount.Normal = "Mounts"
 AutoBarButtonCooldownPotionRejuvenation = 
```

**Comment by illutian** [comment]
Getting this too, but on a different line:

2x AutoBarClassic/AutoBarOptions.lua:754: attempt to index field 'Bar' (a nil value)
[string "@AutoBarClassic/AutoBarOptions.lua"]:754: in function <AutoBarClassic/AutoBarOptions.lua:753>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@AdvancedInterfaceOptions/libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:839: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:661>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...ancedInterfaceOptions/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@AdvancedInterfaceOptions/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@AdvancedInterfaceOptions/libs/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...ions/libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Bar' (a nil value)"
AB = <table> {
 types = <table> {
 }
 MacroTextCategory = <table> {
 }
 AutoBarConfig = <table> {
 }
 LibKeyBound = <table> {
 }
 ItemsCategory = <table> {
 }
 bar = <table> {
 }
 CategoryClass = <table> {
 }
 UITK = <table> {
 }
 CustomCategory = <table> {
 }
 SpellsCategory = <table> {
 }
 LibStickyFrames = <table> {
 }
 WHATSNEW_TEXT = " - Warlock: Added Fel Armor
 - Added Beacon of Hydraxis to Hearth button
 - Improved datamining of food and drinks
 - I'm not playing WoW, so if things are missing make sure you report them.
|n"
 code = <table> {
 }
 events = <table> {
 }
}
L = <table> {
 Consumable.Buff.Resistance.Target = "Consumable.Buff.Resistance.Target"
 HearthIncludeAncientDalaran = "Include Ancient Dalaran"
 Consumable.Buff Group.Melee.Target = "Buff: Melee Target"
 Show Minimap Icon = "Show Minimap Icon"
 Key Bindings = "Key Bindings"
 Summon A Random Pet = "Summon Random Pet|n|cFFFFD100Summon a random pet from your pet journal|r"
 MountShowSummonRandom = "Summon a Random Favourite Mount"
 Raid 5 = "Raid Moon"
 AutoBarClassBarWarrior = "Warrior"
 Consumable.Buff Group.General.Target = "Buff: General Target"
 Shared = "Shared"
 AutoBarButtonBear = "Bear"
 AutoBarButtonWaterBuff = "Water Buff"
 LEFT = "Left"
 AutoBarButtonTravel = "Travel"
 Muffin.Covenant.Anima = "Muffin.Covenant.Anima"
 Consumable.Weapon Buff.Poison.Instant = "Instant Poison"
 AutoBarButtonBoomkinTree = "Tree of Life / Boomkin"
 Muffin.Covenant.Wildseed = "Muffin.Covenant.Wildseed"
 Muffin.Order Hall.Order Resources = "Muffin.Order Hall.Order Resources"
 Consumable.Food.Pet.Fungus = "Food: Pet Fungus"
 Snap Bars while moving = "Snap Bars while moving"
 Reset Bars = "Reset Bars"
 Consumable.Cooldown.Stone.Rejuvenation.Dreamless Sleep = "Dreamless Sleep"
 Consumable.Food.Edible.Combo.Conjured = "Food: combo health & mana gain, conjured"
 AutoBarButtonER = "ER"
 Consumable.Buff.Resistance.Self = "Consumable.Buff.Resistance.Self"
 AutoBarCooldownHeader = "Potion & Stone Cooldown"
 Non Combat Only = "Non Combat Only"
 Consumable.Buff Group.Caster.Target = "Buff: Caster Target"
 AutoBarButtonMiscFun = "Misc, Fun"
 Remove this Button from the Bar = "Remove this Button from the Bar"
 Misc.Spell.Mount.Flying.Fast = "Mounts: Fast Flying"
 Muffin.Skill.Archaeology.Lodestone = "Muffin.Skill.Archaeology.Lodestone"
 AutoBarCustomBarBandages = "Bandages"
 BOTTOMLEFT = "Bottom Left"
 Consumable.Buff.Armor = "Buff: Armor"
 AutoBarClassBarRogue = "Rogue"
 Ctrl-Shift-Click = "Ctrl-Shift-Click"
 Spell.Totem.Earth = "Earth Totem"
 Always keep Popups open for %s = "Always keep Popups open for %s"
 AutoBarButtonToyBox = "Toy Box"
 Spell.Class.Pets2 = "Pet Combat"
 SelfCast using Right click = "SelfCast using Right click"
 ToyBoxOnlyFavourites = "Only Show Favourites"
 BOTTOMRIGHT = "Bottom Right"
 Misc.Lockboxes = "Lockboxes"
 SLASHCMD_LONG = "autobar"
 Consumable.Buff.Health = "Buff: Health"
 MountShowNonFavourites = "Show Non-Favourites"
 Consumable.Buff Pet = "Buff: Pet"
 Spell.Track = "Spell.Track"
 AutoBarButtonSunsongRanch = "Sunsong Ranch"
 U = "U"
 Button Height = "Button Height"
 Spell.Sting = "Sting"
 AutoBarButtonRotationDrums = "Rotation: Drums"
 Tradeskill.Tool.Fishing.Tool = "Fishing Poles"
 Misc.Spell.Mount.Flying.Slow = "Mounts: Slow Flying"
 Skin the Buttons = "Skin the Buttons"
 Consumable.Bandage.Battleground.Warsong Gulch = "Warsong Bandages"
 Consumable.Buff.Dodge = "Buff: Dodge"
 Raid 2 = "Raid Circle"
 TOP = "Top"
 Consumable.Cooldown.Potion.Health.PvP = "Heal Potions: Battleground"
 Consumable.Buff.Intellect = "Buff: Intellect"
 Consumable.Weapon Buff.Poison.Crippling = "Crippling Poison"
 FadeOut takes this amount of time. = "FadeOut takes this amount of time"
 Hide %s = "Hide %s"
 Consumable.Buff Type.Guardian = "Buff: Guardian Elixir"
 Misc.Usable.Fun = "Fun Items"
 Muffin.Order Hall.Ancient Mana = "Muffin.Order Hall.Ancient Mana"
 Misc.Mount.Normal = "Mounts"
 AutoBarButtonCooldownPoti   **((It's cut off))**

**Comment by MuffinManKen** [comment]
Should be fixed now.
