### ISSUE TITLE
Addon won't load with todays patch (V11.0.2.56110)

### ISSUE THREAD

**Issue by Skuriles** [MuffinManKen/AutoBar#64]
```
Message: Interface/AddOns/AutoBar/Core.lua:213: attempt to call field 'GetAddOnMetadata' (a nil value)
Time: Wed Aug 14 05:53:59 2024
Count: 8
Stack: Interface/AddOns/AutoBar/Core.lua:213: attempt to call field 'GetAddOnMetadata' (a nil value)
[string "@Interface/AddOns/AutoBar/Core.lua"]:213: in function `InitializeZero'
[string "@Interface/AddOns/AutoBar/Core.lua"]:400: in function `?'
[string "@Interface/AddOns/AutoBar/Core.lua"]:116: in function <Interface/AddOns/AutoBar/Core.lua:111>

```

Get this on start and each load (zone change/instances etc)

**Comment by Addonman** [comment]
Message: Interface/AddOns/AutoBar/AutoBarGlobals.lua line 541:
   attempt to index global 'C_Addons' (a nil value)
Debug:
   [string "@Interface/AddOns/AutoBar/AutoBarGlobals.lua"]:541: in main chunk
Locals:
_ = nil
AB = <table> {
 UITK = <table> {
 }
 code = <table> {
 }
 LibKeyBound = <table> {
 }
 LibStickyFrames = <table> {
 }
 types = <table> {
 }
}
code = <table> {
}
types = <table> {
}
string = <table> {
}
ver_string = "11.0.2"
api_version_temp = <table> {
 1 = "11"
 2 = "0"
 3 = "2"
}
macro_text_guid_index = 0
logItems = <table> {
}
logMemory = <table> {
}
event_name_colour = "|cFFFFFF7F"
(*temporary) = nil
(*temporary) = 9
(*temporary) = nil
(*temporary) = nil
(*temporary) = 9
(*temporary) = 10
(*temporary) = nil
(*temporary) = "attempt to index global 'C_Addons' (a nil value)"

**Comment by Addonman** [comment]
Message: Interface/AddOns/AutoBar/AutoBarClassBasicButton.lua line 19:
   Cannot find a library instance of AceOO-2.0.
Debug:
   [string "=[C]"]: error()
   [string "@Interface/AddOns/AutoBar/libs/MMGHACKAceLibrary/MMGHACKAceLibrary.lua"]:490: MMGHACKAceLibrary()
   [string "@Interface/AddOns/AutoBar/AutoBarClassBasicButton.lua"]:19: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of AceOO-2.0."

**Comment by Phil-Libra** [comment]
I fixed most errors but still get this:
`Message: bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
Time: Sat Aug 17 15:28:45 2024
Count: 1
Stack: bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
[string "=[C]"]: in function `GetSpellInfo'
[string "@Interface/AddOns/AutoBar/AutoBarCategory.lua"]:125: in function <Interface/AddOns/AutoBar/AutoBarCategory.lua:113>
[string "@Interface/AddOns/AutoBar/AutoBarCategory.lua"]:396: in function `Refresh'
[string "@Interface/AddOns/AutoBar/AutoBarCategory.lua"]:373: in function `new'
[string "@Interface/AddOns/AutoBar/retail/ABCategoryData_retail.lua"]:99: in function `InitializeCategories'
[string "@Interface/AddOns/AutoBar/AutoBarCategory.lua"]:547: in function `InitializeAllCategories'
[string "@Interface/AddOns/AutoBar/Core.lua"]:733: in function `Initialize'
[string "@Interface/AddOns/AutoBar/Core.lua"]:217: in function `InitializeZero'
[string "@Interface/AddOns/AutoBar/Core.lua"]:400: in function `?'
[string "@Interface/AddOns/AutoBar/Core.lua"]:116: in function <Interface/AddOns/AutoBar/Core.lua:111>

Locals: (*temporary) = "bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))"
`
