### ISSUE TITLE
Add demonic healthstone to Health bars

### ISSUE THREAD

**Issue by jonespm** [MuffinManKen/AutoBar#69]
It looks like the new Demonic Healthstone (224464) isn't available when created by a warlock. The regular ones do appear in the Health button. 

Thanks for the great addon!

**Comment by goldenpipes** [comment]
Is this not a thing? I swear my healthstones show up in classic under the health potions button.

**Comment by jonespm** [comment]
Not sure, I started playing Warlock and maybe it's just for the newer Demonic Healthstone that was added in War Within? But I also haven't noticed regular Healthstones in there. I'll double check those when I grab one again.

**Comment by MuffinManKen** [comment]
This should be fixed in the latest version (11.0.2.03)
