### ISSUE TITLE
extra bar not showing?

### ISSUE THREAD

**Issue by Zerocharisma101** [MuffinManKen/AutoBar#70]
so i dont know what i did haha but i was messing with the extra bar to get from laying down to standing up got it the way i wanted then realized everything was gone the bar shows green but the mount,hearthstone, and other misc stuff was no longer showing haha....help me with my mistake!! 

![Capture](https://github.com/user-attachments/assets/00dc1b0f-fb7e-47b6-a946-f92e6bebefe2)

**Comment by MuffinManKen** [comment]
Please go to the Bars tab and select the Extras bar:
Is it Enabled?
Is it the Hide option set?

**Comment by Zerocharisma101** [comment]
![image](https://github.com/user-attachments/assets/a943b165-5c86-4903-8fa7-1411ed5b2e8c)
 this is what is looks like for me

**Comment by Zerocharisma101** [comment]
![image](https://github.com/user-attachments/assets/aa41302f-9bf6-400d-9f2f-d2df983b5dcd)

**Comment by Zerocharisma101** [comment]
![image](https://github.com/user-attachments/assets/dd8299c3-5dbe-4641-adaa-bd91fa0990d4)

**Comment by MuffinManKen** [comment]
Change the Alpha to 1

**Comment by MuffinManKen** [comment]
Did it work?

**Comment by Zerocharisma101** [comment]
Apologies I been working haha yes it did thank you! 

Yahoo Mail: Search, Organize, Conquer 
 
  On Fri, Oct 18, 2024 at 11:56 AM, Ken ***@***.***> wrote:   


Did it work?
