### ISSUE TITLE
Buff food not showing

### ISSUE THREAD

**Issue by dshookowsky** [MuffinManKen/AutoBar#71]
With the latest version, buff food (Tender Wolf Steak, Glossy Mightfish) isn't showing. It's only showing Alterac Manna Biscuit and Morning Glory Dew.

**Comment by MuffinManKen** [comment]
What version are you using?

**Comment by dshookowsky** [comment]
AutoBarClassic_1.15.4.00

**Comment by MuffinManKen** [comment]
Should be fixed in v1.15.4.01
