### ISSUE TITLE
new issue...now my extra appears over my bags? and cant figure out how to get mount bar to stick out to left not up or down

### ISSUE THREAD

**Issue by Zerocharisma101** [MuffinManKen/AutoBar#73]
sorry new issue haha....so my extra bar now shows over my bags kinda annoying lol and then the mounts either only go up or down i want them to go straight out ? if that makes sense haha..
![image](https://github.com/user-attachments/assets/ae52f7b9-f75d-4887-87eb-5273b0bf7a06)
![image](https://github.com/user-attachments/assets/d50c1d33-dad5-431c-ae31-488c83f01e66)

**Comment by Zerocharisma101** [comment]
basically it is covering my  hearth stones and i want it all to just shoot out stright left like how it is but not down 1 then left

**Comment by MuffinManKen** [comment]
The popup direction is set on the Bar.  On the button itself, you can change the "Square Popups" and the "Max Popup Height" to further customize the behaviour.
